apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: wordpress
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk       # rootpassword
  mysql-user: d3B1c2Vy                         # wpuser
  mysql-password: d2VsY29tZUAxMjM=             # welcome@123

   